from abc import ABC

from domain.user.model import User


class UserRepository(ABC):
    def get_by_id(self, id: str) -> User | None: ...
    def create(self, user: User): ...
    def delete(self, user: User): ...
